# Generated by Django 2.2.17 on 2021-01-27 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportaj_app', '0010_auto_20210127_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klub',
            name='header_images',
        ),
        migrations.AlterField(
            model_name='klub',
            name='logo',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='SlikaKluba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=512)),
                ('opis', models.CharField(max_length=4096)),
                ('slike', models.FileField(upload_to='header_slike/')),
                ('klub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slike', to='sportaj_app.Klub')),
            ],
            options={
                'verbose_name': 'Slika',
                'verbose_name_plural': 'Slike',
            },
        ),
    ]
