# Generated by Django 2.2.17 on 2021-01-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportaj_app', '0011_auto_20210127_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klub',
            name='logo',
            field=models.FileField(blank=True, upload_to='klub_logo/'),
        ),
    ]
