# Generated by Django 2.2.17 on 2021-01-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportaj_app', '0014_klub_urnik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klub',
            name='logo',
            field=models.ImageField(blank=True, upload_to='klub_logo/'),
        ),
        migrations.AlterField(
            model_name='slikakluba',
            name='slika',
            field=models.ImageField(upload_to='header_slike/'),
        ),
    ]
