# Generated by Django 2.2.17 on 2021-02-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportaj_app', '0015_auto_20210129_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='klub',
            name='location_friendly',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
