# Generated by Django 2.2.18 on 2021-02-16 20:21

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('sportaj_app', '0016_klub_location_friendly'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Custom tag',
                'verbose_name_plural': 'Custom tags',
            },
        ),
        migrations.RemoveField(
            model_name='klub',
            name='tags',
        ),
        migrations.CreateModel(
            name='PanogaTag',
            fields=[
                ('customtag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sportaj_app.CustomTag')),
            ],
            options={
                'abstract': False,
            },
            bases=('sportaj_app.customtag',),
        ),
        migrations.CreateModel(
            name='StarostTag',
            fields=[
                ('customtag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sportaj_app.CustomTag')),
            ],
            options={
                'abstract': False,
            },
            bases=('sportaj_app.customtag',),
        ),
        migrations.CreateModel(
            name='VadbaTag',
            fields=[
                ('customtag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sportaj_app.CustomTag')),
            ],
            options={
                'abstract': False,
            },
            bases=('sportaj_app.customtag',),
        ),
        migrations.CreateModel(
            name='TaggedItemVadba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportaj_app.Klub')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sportaj_app_taggeditemvadba_items', to='sportaj_app.VadbaTag')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedItemStarost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportaj_app.Klub')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sportaj_app_taggeditemstarost_items', to='sportaj_app.StarostTag')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedItemPanoga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportaj_app.Klub')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sportaj_app_taggeditempanoga_items', to='sportaj_app.PanogaTag')),
            ],
        ),
        migrations.AddField(
            model_name='klub',
            name='panoge_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='panoge', through='sportaj_app.TaggedItemPanoga', to='sportaj_app.PanogaTag', verbose_name='Panoga'),
        ),
        migrations.AddField(
            model_name='klub',
            name='starosti_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='starosti', through='sportaj_app.TaggedItemStarost', to='sportaj_app.StarostTag', verbose_name='Starost'),
        ),
        migrations.AddField(
            model_name='klub',
            name='vadba_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='vadbe', through='sportaj_app.TaggedItemVadba', to='sportaj_app.VadbaTag', verbose_name='Vadba'),
        ),
    ]
