# Generated by Django 2.2.18 on 2021-02-16 21:08

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('sportaj_app', '0017_auto_20210216_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpolTag',
            fields=[
                ('customtag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sportaj_app.CustomTag')),
            ],
            options={
                'abstract': False,
            },
            bases=('sportaj_app.customtag',),
        ),
        migrations.CreateModel(
            name='TaggedItemSpol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportaj_app.Klub')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sportaj_app_taggeditemspol_items', to='sportaj_app.SpolTag')),
            ],
        ),
        migrations.AddField(
            model_name='klub',
            name='spoli_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='spoli', through='sportaj_app.TaggedItemSpol', to='sportaj_app.SpolTag', verbose_name='Spol'),
        ),
    ]
