# Generated by Django 2.2.18 on 2021-02-16 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportaj_app', '0018_auto_20210216_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klub',
            old_name='vadba_tags',
            new_name='vadbe_tags',
        ),
    ]
