# Generated by Django 2.2.18 on 2021-02-17 07:34

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportaj_app', '0019_auto_20210216_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtag',
            name='colour',
            field=colorfield.fields.ColorField(default='#2643E900', max_length=18),
        ),
    ]
