# Generated by Django 2.2.18 on 2021-02-17 08:01

from django.db import migrations
import faicon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sportaj_app', '0021_auto_20210217_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtag',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, max_length=50),
        ),
    ]
