# Generated by Django 2.2.19 on 2021-04-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportaj_app', '0022_customtag_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klub',
            old_name='panoge_tags',
            new_name='panoga_tags',
        ),
        migrations.RenameField(
            model_name='klub',
            old_name='spoli_tags',
            new_name='spol_tags',
        ),
        migrations.RenameField(
            model_name='klub',
            old_name='starosti_tags',
            new_name='starost_tags',
        ),
        migrations.RenameField(
            model_name='klub',
            old_name='vadbe_tags',
            new_name='vadba_tags',
        ),
    ]
