# Generated by Django 2.2.19 on 2021-04-15 19:34

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('sportaj_app', '0023_auto_20210415_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenaTag',
            fields=[
                ('customtag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sportaj_app.CustomTag')),
            ],
            options={
                'abstract': False,
            },
            bases=('sportaj_app.customtag',),
        ),
        migrations.CreateModel(
            name='TipTag',
            fields=[
                ('customtag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sportaj_app.CustomTag')),
            ],
            options={
                'abstract': False,
            },
            bases=('sportaj_app.customtag',),
        ),
        migrations.CreateModel(
            name='UrnikTag',
            fields=[
                ('customtag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sportaj_app.CustomTag')),
            ],
            options={
                'abstract': False,
            },
            bases=('sportaj_app.customtag',),
        ),
        migrations.CreateModel(
            name='TaggedItemUrnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportaj_app.Klub')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sportaj_app_taggeditemurnik_items', to='sportaj_app.UrnikTag')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedItemTip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportaj_app.Klub')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sportaj_app_taggeditemtip_items', to='sportaj_app.TipTag')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedItemCena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportaj_app.Klub')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sportaj_app_taggeditemcena_items', to='sportaj_app.CenaTag')),
            ],
        ),
        migrations.AddField(
            model_name='klub',
            name='cena_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='urniki', through='sportaj_app.TaggedItemCena', to='sportaj_app.CenaTag', verbose_name='Cena'),
        ),
        migrations.AddField(
            model_name='klub',
            name='tip_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='tipi', through='sportaj_app.TaggedItemTip', to='sportaj_app.TipTag', verbose_name='Tip'),
        ),
        migrations.AddField(
            model_name='klub',
            name='urnik_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='urniki', through='sportaj_app.TaggedItemUrnik', to='sportaj_app.UrnikTag', verbose_name='Urnik'),
        ),
    ]
