# Generated by Django 2.2.19 on 2021-04-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportaj_app', '0024_auto_20210415_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klub',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
