# Generated by Django 2.2.19 on 2021-04-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportaj_app', '0025_auto_20210415_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='klub',
            name='urnikPovezava',
            field=models.URLField(blank=True, null=True),
        ),
    ]
