# Generated by Django 2.2.19 on 2021-04-16 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportaj_app', '0026_klub_urnikpovezava'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urniktag',
            name='customtag_ptr',
        ),
        migrations.RemoveField(
            model_name='klub',
            name='urnik_tags',
        ),
        migrations.DeleteModel(
            name='TaggedItemUrnik',
        ),
        migrations.DeleteModel(
            name='UrnikTag',
        ),
    ]
